### ISSUE TITLE
update the ABN engine to 1.4

### ISSUE THREAD

**Issue by fruitl00p** [fruitl00p/php-mt940#36]
According to the docs several fields have been updated for the new SWIFT + SEPA specs. Some additional tests are needed too
- [ ] decide on handling BC issues (keep old or dump it?)
- [ ] update the engine
- [ ] add tests to confirm the 1.4 spec

**Comment by Jicked** [comment]
The Rabobank also published a new version of there MT940 export.
https://www.rabobank.nl/bedrijven/betalen/zakelijk-internetbankieren/internetbankieren-professional/support/bestanden/

I just registered on github to post this comment, so I don't know if I am able to submit some changes, but regex in the parser for the description needs to be changed:
preg_match('#/REMI/(.*?)/(ISDT|CSID|RTRN)/#s', $description, $results)

It is possible for the REMI tag to end with a newline instead of another tag. And it is aldo possible to end with /PURP/. /ISDT/ is not supported anymore.

The bank says that the new format will be used mid-april, but we already had a customer that imported the new format unfortunately.

Just to let you know.
If you need a test file, let me know I will request one

**Comment by fruitl00p** [comment]
@Jicked I'd still like to support both the old and new Rabo versions :) Test files are always welcome. If you want you could fork this repo, make changes (incl adding new tests for the new file versions) and make a pullrequest. This will trigger automatic builds to ensure (for the tests that we have atleast) everything still works :)

**Comment by fruitl00p** [comment]
It seems this is no longer an issue due to the updates in june last year. This should be fixed with the new [1.3.0](https://github.com/fruitl00p/php-mt940/tree/1.3.0) release cut just now ;)
